spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: didisk*159
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update